services:
  indexer:
    image: '${DOCKER_IMAGE_IDX?Variable not set}:${TAG-latest}'
    restart: always
    networks:
      - tp-backend-net
#    logging:
#      driver: loki
#      options:
#        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
#        loki-retries: "5"
#        loki-batch-size: "100"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8012/api/v1/health-check/" ]
      interval: 10s
      timeout: 5s
      retries: 5

  classifier:
    image: '${DOCKER_IMAGE_CLA?Variable not set}:${TAG-latest}'
    restart: always
    networks:
      - tp-backend-net
#    logging:
#      driver: loki
#      options:
#        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
#        loki-retries: "5"
#        loki-batch-size: "100"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8012/api/v1/health-check/" ]
      interval: 10s
      timeout: 5s
      retries: 5

  llm:
    image: '${DOCKER_IMAGE_LLM?Variable not set}:${TAG-latest}'
    restart: always
    networks:
      - tp-backend-net
#    logging:
#      driver: loki
#      options:
#        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
#        loki-retries: "5"
#        loki-batch-size: "100"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8012/api/v1/health-check/" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pii:
    image: '${DOCKER_IMAGE_PII?Variable not set}:${TAG-latest}'
    restart: always
    networks:
      - tp-backend-net
#    logging:
#      driver: loki
#      options:
#        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
#        loki-retries: "5"
#        loki-batch-size: "100"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8012/api/v1/health-check/" ]
      interval: 10s
      timeout: 5s
      retries: 5

#networks:
#  tp-backend:
#    # Allow setting it to false for testing
#    external: false
networks:
  tp-backend-net:
    external: true
    name: tp-backend-net
